name: XCS330_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cloudpickle=2.0.0
  - cycler=0.11.0
  - h5py=3.7.0
  - lockfile=0.12.2
  - opt-einsum=3.0.0
  - packaging=22.0
  - pandas=1.5.2
  - pickleshare=0.7.5
  - python-dateutil=2.8.2
  - requests=2.28.1
  - scipy=1.10.0
  - six=1.16.0
  - scikit-learn=1.1.3
  - tensorboard=2.10.0
  - pytest=7.1.2
  - imageio=2.19.3
  - svglib=1.5.1
  - googledrivedownloader=0.4
  - matplotlib=3.7.0
  - pip=22.3.1
  - pip:
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==1.13.1+cu116
    - torchvision==0.14.1+cu116
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - huggingface-hub==0.10.0
    - transformers==4.23.0
    - datasets==2.5.2
    - numpy==1.23.3